### ISSUE TITLE
Генерировать событие при открытии двери

### ISSUE THREAD

**Issue by gorbunovav** [Anonym-tsk/smart-domofon#13]
День добрый!

В сценариях автоматизации бывает необходимо реагировать на открытие двери домофоном.
Можно отслеживать изменения статусов, но это представляет не очень надежным + есть разные последовательности смены статусов.

В ESPHome есть возможность генерировать события в Home Assistant. На мой взгляд было бы удобно отправлять такое событие при выполнении действия открытия.

**Comment by Anonym-tsk** [comment]
Пришлось откатить. Не работает с mqtt.
Если будет идея как сделать универсально - добавим.

**Comment by gorbunovav** [comment]
@Anonym-tsk  сделал через вызов скриптов отправки событий, варианты которых определены в `api.yaml` и в `mqtt.yaml` с соответствующей реализацией.

**Comment by Anonym-tsk** [comment]
В последней прошивке добавлен сенсор `Domofon Action`. Подробнее в Readme
