### ISSUE TITLE
2023.12 pin reuse validation

### ISSUE THREAD

**Issue by odddim0n** [Anonym-tsk/smart-domofon#16]
После обновления ESPHome до версии 2023.12 не компилируется конфиг, не проходит валидацию переиспользования пинов (https://esphome.io/changelog/2023.12.0.html). Проблема с $pin_led_blue, который определён как Status LED в light.yaml, а также как led_blue в output.yaml.
"The error can be bypassed by specifically adding another config item to all of the duplicate pin definitions": переменная allow_other_uses (Optional, boolean)

**Comment by Anonym-tsk** [comment]
Исправлено
