### ISSUE TITLE
Не компилится конфиг

### ISSUE THREAD

**Issue by Mioze** [Anonym-tsk/smart-domofon#18]
Похоже обновления ESP не дают компилится конфигу
INFO ESPHome 2023.12.5
INFO Reading configuration /config/esphome/domofon.yaml...
Failed config

switch.template: [source <unicode string>:237]
  platform: template
  name: Domofon automatically open
  id: auto_open
  icon: mdi:door-open
  optimistic: True
  
  The restore_state option has been removed in 2023.7.0. Use the restore_mode option instead.
  restore_state: True
  on_turn_on: 
    - switch.turn_off: auto_open_once
    - switch.turn_off: auto_reject
    - script.execute: state_no_call
  on_turn_off: 
    script.execute: state_no_call
switch.template: [source <unicode string>:251]
  platform: template
  name: Domofon automatically open once
  id: auto_open_once
  icon: mdi:door-open
  optimistic: True
  
  The restore_state option has been removed in 2023.7.0. Use the restore_mode option instead.
  restore_state: True
  on_turn_on: 
    - switch.turn_off: auto_open
    - switch.turn_off: auto_reject
    - script.execute: state_no_call
  on_turn_off: 
    script.execute: state_no_call
switch.template: [source <unicode string>:265]
  platform: template
  name: Domofon automatically reject
  id: auto_reject
  icon: mdi:door-closed-lock
  optimistic: True
  
  The restore_state option has been removed in 2023.7.0. Use the restore_mode option instead.
  restore_state: True
  on_turn_on: 
    - switch.turn_off: auto_open
    - switch.turn_off: auto_open_once
    - script.execute: state_no_call
  on_turn_off: 
    script.execute: state_no_call

**Comment by Anonym-tsk** [comment]
У вас очень старая прошивка. Обновитесь.

**Comment by Mioze** [comment]
Получается это у Вас конфиг устаревший
В этих разделах:
```
# Automatically open door switch
# Automatically open door once switch
# Automatically reject call switch
```
поменял с:    restore_state: true
на: restore_mode: ALWAYS_ON
только тогда конфиг залетел в esp
нововведение Esphome в home assistant...

**Comment by Anonym-tsk** [comment]
Вы видимо используете прошивку из каталога esphome. Она давно не поддерживается, но я внесу изменения. Спасибо.

**Comment by 19leva89** [comment]
День добрый, можете помочь? Не компилируется(

```
INFO ESPHome 2024.6.4
INFO Reading configuration /config/esphome/domofon.yaml...
INFO Cloning https://github.com/Anonym-tsk/smart-domofon.git@master
INFO Fetching master
Failed config

ota.unknown: [source /data/packages/2ae9eeeb/ge1mer/esphome/packages/base.yaml:35]
  
  'ota' requires a 'platform' key but it was not specified.
  password: esphome
```

**Comment by Anonym-tsk** [comment]
> можете помочь?

Внес исправления в код.
Удалите каталог `/config/.esphome/packages` перед сборкой, должно заработать.

**Comment by 19leva89** [comment]
Да все ок, спасибо!

> > можете помочь?
> 
> Внес исправления в код. Удалите каталог `/config/.esphome/packages` перед сборкой, должно заработать.
