### ISSUE TITLE
Ошибка обновления ESPHome 2024.10.1

### ISSUE THREAD

**Issue by odddim0n** [Anonym-tsk/smart-domofon#19]
Ошибка при попытке обновления до ESPHome 2024.10.1. Журнал обновления:
Compiling .pioenvs/domofon/src/main.cpp.o
<command-line>: warning: "MMU_IRAM_SIZE" redefined
<command-line>: note: this is the location of the previous definition
<command-line>: warning: "MMU_ICACHE_SIZE" redefined
<command-line>: note: this is the location of the previous definition
Compiling .pioenvs/domofon/FrameworkArduino/umm_malloc/umm_malloc.cpp.o
<command-line>: warning: "MMU_IRAM_SIZE" redefined
<command-line>: note: this is the location of the previous definition
<command-line>: warning: "MMU_ICACHE_SIZE" redefined
<command-line>: note: this is the location of the previous definition
/data/cache/platformio/packages/framework-arduinoespressif8266/cores/esp8266/umm_malloc/umm_malloc.cpp: In function 'void umm_init_iram()':
/data/cache/platformio/packages/framework-arduinoespressif8266/cores/esp8266/umm_malloc/umm_malloc.cpp:593:22: error: 'mmu_sec_heap' was not declared in this scope
  593 |     umm_init_iram_ex(mmu_sec_heap(), mmu_sec_heap_size(), true);
      |                      ^~~~~~~~~~~~
/data/cache/platformio/packages/framework-arduinoespressif8266/cores/esp8266/umm_malloc/umm_malloc.cpp:593:38: error: 'mmu_sec_heap_size' was not declared in this scope; did you mean 'umm_free_heap_size'?
  593 |     umm_init_iram_ex(mmu_sec_heap(), mmu_sec_heap_size(), true);
      |                                      ^~~~~~~~~~~~~~~~~
      |                                      umm_free_heap_size
*** [.pioenvs/domofon/FrameworkArduino/umm_malloc/umm_malloc.cpp.o] Error 1
========================= [FAILED] Took 14.89 seconds =========================

**Comment by Alexamig** [comment]
Попробуйте так сделать в base.yaml:
  platformio_options:
    build_flags: -DBEARSSL_SSL_BASIC -DMMU_IRAM_SIZE=0xC000 -DMMU_ICACHE_SIZE=0x4000 -DMMU_IRAM_HEAP
на
  platformio_options:
    build_flags: -DBEARSSL_SSL_BASIC -DMMU_IRAM_SIZE=0xC000 -DMMU_ICACHE_SIZE=0x4000 -D PIO_FRAMEWORK_ARDUINO_MMU_CUSTOM
и все пойдет

**Comment by odddim0n** [comment]
Спасибо!
Если у кого-то аналогичная ситуация: base.yaml - это часть репозитория, поэтому проще в конфиге устройства в ESPHome (domofon.yaml) в раздел esphome: добавить по аналогии с base.yaml замену
  platformio_options:
    build_flags: -DBEARSSL_SSL_BASIC -DMMU_IRAM_SIZE=0xC000 -DMMU_ICACHE_SIZE=0x4000 -D PIO_FRAMEWORK_ARDUINO_MMU_CUSTOM

**Comment by eratnik** [comment]
> Попробуйте так сделать в base.yaml: platformio_options: build_flags: -DBEARSSL_SSL_BASIC -DMMU_IRAM_SIZE=0xC000 -DMMU_ICACHE_SIZE=0x4000 -DMMU_IRAM_HEAP на platformio_options: build_flags: -DBEARSSL_SSL_BASIC -DMMU_IRAM_SIZE=0xC000 -DMMU_ICACHE_SIZE=0x4000 -D PIO_FRAMEWORK_ARDUINO_MMU_CUSTOM и все пойдет

Спасибо, ваш совет помог, но не полностью - не работает беззвучный режим. Оно пытается переключать, лампочка пару раз моргает, но выключается, а в логах пишет: 
```
[20:24:49][D][switch:012]: 'Domofon mute sound' Turning ON.
[20:24:49][D][switch:055]: 'Domofon mute sound': Sending state ON
[20:24:51][D][sensor:093]: 'Domofon Heap Size': Sending state 20904.00000 bytes with 0 decimals of accuracy
[20:24:52][I][safe_mode:041]: Boot seems successful; resetting boot loop counter
WARNING domofon @ 192.168.1.68: Connection error occurred: [Errno 104] Connection reset by peer
INFO Processing unexpected disconnect from ESPHome API for domofon @ 192.168.1.68
WARNING Disconnected from API
INFO Successfully connected to domofon @ 192.168.1.68 in 0.004s
INFO Successful handshake with domofon @ 192.168.1.68 in 3.002s
[20:25:31][D][api:103]: Accepted 192.168.1.90
[20:25:31][W][component:237]: Component api took a long time for an operation (312 ms).
[20:25:31][W][component:238]: Components should block for at most 30 ms.
[20:25:32][D][api.connection:1446]: Home Assistant 2024.10.4 (192.168.1.90): Connected successfully
[20:25:39][D][sensor:093]: 'Domofon Heap Size': Sending state 21944.00000 bytes with 0 decimals of accuracy
```
Остальные режимы вроде работают, беззвучный и однократный беззвучный не хотят.
Может есть мысли, чем можно помочь? На предыдущей версии ESPhome все работало

**Comment by Alexamig** [comment]
> > Попробуйте так сделать в base.yaml: platformio_options: build_flags: -DBEARSSL_SSL_BASIC -DMMU_IRAM_SIZE=0xC000 -DMMU_ICACHE_SIZE=0x4000 -DMMU_IRAM_HEAP на platformio_options: build_flags: -DBEARSSL_SSL_BASIC -DMMU_IRAM_SIZE=0xC000 -DMMU_ICACHE_SIZE=0x4000 -D PIO_FRAMEWORK_ARDUINO_MMU_CUSTOM и все пойдет
> 
> Спасибо, ваш совет помог, но не полностью - не работает беззвучный режим. Оно пытается переключать, лампочка пару раз моргает, но выключается, а в логах пишет:
> 
> ```
> [20:24:49][D][switch:012]: 'Domofon mute sound' Turning ON.
> [20:24:49][D][switch:055]: 'Domofon mute sound': Sending state ON
> [20:24:51][D][sensor:093]: 'Domofon Heap Size': Sending state 20904.00000 bytes with 0 decimals of accuracy
> [20:24:52][I][safe_mode:041]: Boot seems successful; resetting boot loop counter
> WARNING domofon @ 192.168.1.68: Connection error occurred: [Errno 104] Connection reset by peer
> INFO Processing unexpected disconnect from ESPHome API for domofon @ 192.168.1.68
> WARNING Disconnected from API
> INFO Successfully connected to domofon @ 192.168.1.68 in 0.004s
> INFO Successful handshake with domofon @ 192.168.1.68 in 3.002s
> [20:25:31][D][api:103]: Accepted 192.168.1.90
> [20:25:31][W][component:237]: Component api took a long time for an operation (312 ms).
> [20:25:31][W][component:238]: Components should block for at most 30 ms.
> [20:25:32][D][api.connection:1446]: Home Assistant 2024.10.4 (192.168.1.90): Connected successfully
> [20:25:39][D][sensor:093]: 'Domofon Heap Size': Sending state 21944.00000 bytes with 0 decimals of accuracy
> ```
> 
> Остальные режимы вроде работают, беззвучный и однократный беззвучный не хотят. Может есть мысли, чем можно помочь? На предыдущей версии ESPhome все работало
-----------------------------------------------------------------------------------------------------------------------------------------


Да есть такое что-то неправильно стало работать)) Заметил, что uptime стал часто сбрасываться. Я автоматизацией с 12 ночи ставлю без звука режим и заметил что он постоянно стал скидываться на простой и uptime заново с 0 отсчитывает.
Убрал лишний мусор и все нормализовалось, работает на всех режимах отлично.

![2024-11-15 09 15 51](https://github.com/user-attachments/assets/9560fa75-129a-4408-83da-e968c9f88074)


В base.yaml 
```
esphome:
  name: $mdns_name
  # build_path: $build_path
  platform: ESP8266
  board: $board
  comment: "espdomofon.ru"
  esp8266_restore_from_flash: true
  project:
    name: "espdomofon.ru"
    version: "1.6.2"
  # platformio_options:
  #   build_flags: -DBEARSSL_SSL_BASIC -DMMU_IRAM_SIZE=0xC000 -DMMU_ICACHE_SIZE=0x4000 -D PIO_FRAMEWORK_ARDUINO_MMU_CUSTOM
  on_boot:
    priority: 600
    then:
      - script.execute: state_ready
      - light.turn_on:
          id: rgb_led
          effect: "Domofon"
```

**Comment by eratnik** [comment]
> Да есть такое что-то неправильно стало работать)) Заметил, что uptime стал часто сбрасываться. Я автоматизацией с 12 ночи ставлю без звука режим и заметил что он постоянно стал скидываться на простой и uptime заново с 0 отсчитывает. Убрал лишний мусор и все нормализовалось, работает на всех режимах отлично.
> 
> ![2024-11-15 09 15 51](https://private-user-images.githubusercontent.com/16787405/386479858-9560fa75-129a-4408-83da-e968c9f88074.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE2NTcyNzEsIm5iZiI6MTczMTY1Njk3MSwicGF0aCI6Ii8xNjc4NzQwNS8zODY0Nzk4NTgtOTU2MGZhNzUtMTI5YS00NDA4LTgzZGEtZTk2OGM5Zjg4MDc0LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE1VDA3NDkzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI3MTdlN2QxMWYyMzRjZjY1NjJhMjgxYmU3MGI4NmE0MDI1MjU3YTYzZTc3NTI1YjVkMTk2ZGI5YzE1NDgyODImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.ZGeKjueQC6NkdhJrIeMGuOtK_AsOOV_7aYjd0SQU0C0)
> 
> В base.yaml
> 
> ```
> esphome:
>   name: $mdns_name
>   # build_path: $build_path
>   platform: ESP8266
>   board: $board
>   comment: "espdomofon.ru"
>   esp8266_restore_from_flash: true
>   project:
>     name: "espdomofon.ru"
>     version: "1.6.2"
>   # platformio_options:
>   #   build_flags: -DBEARSSL_SSL_BASIC -DMMU_IRAM_SIZE=0xC000 -DMMU_ICACHE_SIZE=0x4000 -D PIO_FRAMEWORK_ARDUINO_MMU_CUSTOM
>   on_boot:
>     priority: 600
>     then:
>       - script.execute: state_ready
>       - light.turn_on:
>           id: rgb_led
>           effect: "Domofon"
> ```

А можно показать ваш полный файл domofon.yaml? Что-то у меня не "взлетело"
