### ISSUE TITLE
Несколько вопросов по сборке домофона

### ISSUE THREAD

**Issue by runnerfanspb** [Anonym-tsk/smart-domofon#2]
Добрый день. Возникло несколько вопросов по сборке платы. 
1. В случае когда собранная конструкция не подключена к домофону и соответственно нет входящего вызова,  при нажатии на кнопку должно ли щелкать реле?
2. На релейной плате есть перемычка, подскажите в как она должна стоять?
![IMG_20200924_204705_837](https://user-images.githubusercontent.com/58978623/94180739-24e1e900-fea7-11ea-8c87-36272c7d2401.jpg)

**Comment by AlexSZbrn** [comment]
По первому вопросу - не скажу, не собрал ещё, а по второму - так и должна стоять, если релейный модуль питается оттуда же, откуда и контроллер.

**Comment by yamaha252** [comment]
1. Нет, ведь нажатие на кнопку режимы работы переключает
https://github.com/Anonym-tsk/smart-domofon/blob/4cff7c4beba646e1ddbf7923970afd82c0444fe0/esphome/domofon.yaml#L383

**Comment by runnerfanspb** [comment]
> 1. Нет, ведь нажатие на кнопку режимы работы переключает
>    https://github.com/Anonym-tsk/smart-domofon/blob/4cff7c4beba646e1ddbf7923970afd82c0444fe0/esphome/domofon.yaml#L383

С этим тупанул. Спасибо.

**Comment by runnerfanspb** [comment]
> 1. Нет, ведь нажатие на кнопку режимы работы переключает
>    https://github.com/Anonym-tsk/smart-domofon/blob/4cff7c4beba646e1ddbf7923970afd82c0444fe0/esphome/domofon.yaml#L383

Хотя перечитал еще раз описание. При входящем вызову только нажатие на кнопку будет открывать дверь так не должно щелкать и открывать. 
Одиночное нажатие кнопкиНет входящего вызова - включит режим автоматического открытия (открыть один раз по первому нажатию, постоянное открыти по второму)Входящий звонок - откроет дверь

**Comment by yamaha252** [comment]
> > 1. Нет, ведь нажатие на кнопку режимы работы переключает
> >    https://github.com/Anonym-tsk/smart-domofon/blob/4cff7c4beba646e1ddbf7923970afd82c0444fe0/esphome/domofon.yaml#L383
> 
> Хотя перечитал еще раз описание. При входящем вызову только нажатие на кнопку будет открывать дверь так не должно щелкать и открывать.
> Одиночное нажатие кнопкиНет входящего вызова - включит режим автоматического открытия (открыть один раз по первому нажатию, постоянное открыти по второму)Входящий звонок - откроет дверь

Все правильно. Если есть входящий вызов – открывает (щелкает реле несколько раз), если нет (в вашем случае) переключаются режимы по очереди (ничего не щелкает, лапочка меняет режимы)
