### ISSUE TITLE
Моментальный сброс при входящем звонке

### ISSUE THREAD

**Issue by runnerfanspb** [Anonym-tsk/smart-domofon#3]
ДОбрый день. Собрал плату. Почему то при входящем звонке происходит моментальный сброс звонка, даже не успеваешь ответить. Хотя в телегу приходит сообщение открыть или отклонить. Как увеличить время ответа? А то домофон начинает после секунды сигнала переходить в error

**Comment by runnerfanspb** [comment]
Звонок стал проходить, но вот дверь не открывается. Ранее открывалась дверь при авто открытии, или же одиночном открытии. С чем может быть связано?

**Comment by yamaha252** [comment]
Может быть связано с настройками таймингов тут
https://github.com/Anonym-tsk/smart-domofon/blob/4cff7c4beba646e1ddbf7923970afd82c0444fe0/esphome/domofon.yaml#L31

У каждого домофона свои особенности, например мой метаком, не отрабатывает открытие двери, если оно происходит в момент, когда звенит уличный блок 🙂

**Comment by yamaha252** [comment]
Кстати, вот это время `call_end_detect_delay` должно быть не меньше суммы всех задержек указанных ниже с префиксом `relay_`. Иначе, если включено автоматическое открытие, не успеют закончится все операции при первом цикле входящего звонка, запустится повторный цикл и опять начнет молотить тоже самое паралельно.

**Comment by runnerfanspb** [comment]
> Кстати, вот это время `call_end_detect_delay` должно быть не меньше суммы всех задержек указанных ниже с префиксом `relay_`. Иначе, если включено автоматическое открытие, не успеют закончится все операции при первом цикле входящего звонка, запустится повторный цикл и опять начнет молотить тоже самое паралельно.

Решил попробовать последовать вашему совету. А дальше будет видно
![Screenshot_20200926-082652_Home Assistant](https://user-images.githubusercontent.com/58978623/94331094-80f55c00-ffd2-11ea-8f69-425f296d9826.jpg)

**Comment by runnerfanspb** [comment]
не работает. вообще перестал открывать. а где можно посмотреть особенности визита? и может быть проблема, что собирал по схеме, а трубку не ставил перед домофоном,?

**Comment by runnerfanspb** [comment]
Нашел ошибку, т. К. Трубки нет. Надо было резистор поставить

**Comment by yamaha252** [comment]
Нельзя ставить резистор, оно может повлиять на работу всей домофонной сети.

**Comment by Anonym-tsk** [comment]
> Нельзя ставить резистор, оно может повлиять на работу всей домофонной сети.

Трубка даёт сопротивление 50 Ом в линию. Её смело можно заменить на резистор такого же номинала

**Comment by yamaha252** [comment]
> Трубка даёт сопротивление 50 Ом в линию. Её смело можно заменить на резистор такого же номинала

Это я на собственном опыте проверил, поставил резитор и все звонки по подъезду начали идти в последнюю квартиру :)
Возможно связано с тем, что сопротивление в трубке появляется только при поступлении питания на линии, а не всегда.

**Comment by Anonym-tsk** [comment]
> > Трубка даёт сопротивление 50 Ом в линию. Её смело можно заменить на резистор такого же номинала
> 
> Это я на собственном опыте проверил, поставил резитор и все звонки по подъезду начали идти в последнюю квартиру :)
> Возможно связано с тем, что сопротивление в трубке появляется только при поступлении питания на линии, а не всегда.

Сопротивление в трубке есть всегда. По нему вызывная панель определяет подключена ли трубка.
Вы явно что-то сделали не так

**Comment by yamaha252** [comment]
Специалисты сказали, что замыкать линию нельзя. Может зависит от разводки в каждом конкретном случае.
![20201208_202533](https://user-images.githubusercontent.com/4444068/101503474-f480f580-3993-11eb-8100-2d0d969b5faf.jpg)
![20201208_202916](https://user-images.githubusercontent.com/4444068/101503489-f8147c80-3993-11eb-9663-3cd8fc657547.jpg)
