### ISSUE TITLE
перестали приходить сообщения в телеграмм

### ISSUE THREAD

**Issue by runnerfanspb** [Anonym-tsk/smart-domofon#4]
почему то перестали приходить сообщения в телегу при разовом открытии, при автоматическом открытии. При звонке просто сообщение приходит с предложением открыть или отклонить. при открытии с кнопки так же.

**Comment by runnerfanspb** [comment]
в настройках ничего не менял

**Comment by Anonym-tsk** [comment]
Проверить автоматизации в ХА
